name: Publish Mod to external sites

on:
  workflow_dispatch:

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Grant execute permission for .build/deploy.sh
        run: chmod +x .build/deploy.sh
      - name: Deploy
        run: .build/deploy.sh
        env:
          GPG_SECRET: ${{ secrets.GPG_SECRET }}
          GITHUB_TOKEN: ${{ secrets.GH_API_KEY }}